// Code generated by go run ./internal/platform/iam/iamgen/gen; DO NOT EDIT.
// Source: frontend/src/lib/iam/prefixes.ts

package iam

// Menu code prefixes, one var per key of IAM in prefixes.ts.
var (
	Dashboard               = []string{"dashboard"}
	Ess                     = []string{"ess"}
	Items                   = []string{"items"}
	ItemsPurchasing         = []string{"items.product.purchasing", "items.raw-material.purchasing"}
	ItemsInventory          = []string{"items.product.inventory", "items.raw-material.inventory"}
	ItemsApproval           = []string{"items.product.approval", "items.raw-material.approval"}
	ItemsReports            = []string{"items.reports"}
	Pos                     = []string{"pos"}
	PosOperations           = []string{"pos.operations", "pos.cashier.central"}
	PosMemberBills          = []string{"pos.operations.member-bills"}
	PosCatalog              = []string{"pos.catalog"}
	PosKitchen              = []string{"pos.kitchen"}
	PosLoyalty              = []string{"pos.loyalty"}
	PosReports              = []string{"pos.reports"}
	PosSupervisors          = []string{"pos.settings.supervisors"}
	Hris                    = []string{"hris"}
	HrisKepegawaian         = []string{"hris.kepegawaian"}
	HrisWorkforce           = []string{"hris.workforce"}
	HrisCompensation        = []string{"hris.compensation"}
	HrisPerformance         = []string{"hris.performance"}
	HrisRecruitment         = []string{"hris.recruitment"}
	Accounting              = []string{"accounting"}
	Crm                     = []string{"crm"}
	CrmSettings             = []string{"crm.settings"}
	CrmMembers              = []string{"crm.members"}
	CrmInbox                = []string{"crm.members.inbox"}
	CrmReviews              = []string{"crm.members.reviews"}
	CrmLoyalty              = []string{"crm.loyalty"}
	CrmReports              = []string{"crm.reports"}
	CrmPromo                = []string{"crm.promo", "promo"}
	CrmEngagement           = []string{"crm.engagement"}
	CrmMemberReviews        = []string{"crm.members.member-reviews"}
	CrmPartners             = []string{"crm.loyalty.partners"}
	Settings                = []string{"settings"}
	SettingsUsers           = []string{"settings.users"}
	SettingsRoles           = []string{"settings.roles"}
	SettingsMenus           = []string{"settings.menus"}
	SettingsBusiness        = []string{"settings.business"}
	SettingsIntegrations    = []string{"settings.integrations"}
	SettingsAppearance      = []string{"settings.appearance"}
	SettingsPaymentGateways = []string{"settings.payment-gateways"}
	SettingsWaGateway       = []string{"settings.wa_gateway"}
	SettingsAudit           = []string{"settings.audit"}
	Shop                    = []string{"shop"}
	Ticketing               = []string{"ticketing"}
	TicketingAdmin          = []string{"ticketing.settings", "ticketing.tickets", "ticketing.channel-manager", "ticketing.mapping"}
	TicketingOperator       = []string{"ticketing.loket", "ticketing.gate", "ticketing.booking", "ticketing.gate_pass", "ticketing.passes"}
	TicketingReports        = []string{"ticketing.reports"}
	SalesFunnel             = []string{"sales-funnel"}
	Promo                   = []string{"promo", "crm.promo"}
	Dataroom                = []string{"dataroom"}
	Resort                  = []string{"resort"}
	PosWallet               = []string{"pos.loyalty.wallet"}
	GymExercises            = []string{"gym.exercises"}
	GymRaces                = []string{"gym.races"}
	GymIncentives           = []string{"gym.incentives"}
	GymPackages             = []string{"gym.packages"}
	GymCredits              = []string{"gym.credits"}
	GymRules                = []string{"gym.rules"}
	GymScheduling           = []string{"gym.schedule", "gym.sessions", "gym.bookings", "gym.class-types", "gym.coaches"}
	GymCheckin              = []string{"gym.checkin", "gym.sessions"}
	HrisMaster              = []string{"hris.master"}
	HrisOrganization        = []string{"hris.organization"}
	HrisInsights            = []string{"hris.insights"}
	HrisPerformanceAdmin    = []string{"hris.performance.kpi-scorecard", "hris.performance.kpi-config"}
	PosCatalogProducts      = []string{"pos.catalog.products"}
	PosLoyaltySettings      = []string{"pos.loyalty.settings"}
	SettingsBilling         = []string{"settings.billing"}
	ItemsCatalog            = []string{"items", "pos.catalog"}
	ItemsPr                 = []string{"items.general.purchasing.pr", "items.product.purchasing.pr", "items.raw-material.purchasing.pr"}
	ItemsPrApproval         = []string{"items.general.purchasing.approval-pr", "items.product.approval.pr", "items.raw-material.approval.pr"}
)

// ByKey maps the TS key (e.g. "gymPackages") to its prefixes.
var ByKey = map[string][]string{
	"dashboard":               Dashboard,
	"ess":                     Ess,
	"items":                   Items,
	"itemsPurchasing":         ItemsPurchasing,
	"itemsInventory":          ItemsInventory,
	"itemsApproval":           ItemsApproval,
	"itemsReports":            ItemsReports,
	"pos":                     Pos,
	"posOperations":           PosOperations,
	"posMemberBills":          PosMemberBills,
	"posCatalog":              PosCatalog,
	"posKitchen":              PosKitchen,
	"posLoyalty":              PosLoyalty,
	"posReports":              PosReports,
	"posSupervisors":          PosSupervisors,
	"hris":                    Hris,
	"hrisKepegawaian":         HrisKepegawaian,
	"hrisWorkforce":           HrisWorkforce,
	"hrisCompensation":        HrisCompensation,
	"hrisPerformance":         HrisPerformance,
	"hrisRecruitment":         HrisRecruitment,
	"accounting":              Accounting,
	"crm":                     Crm,
	"crmSettings":             CrmSettings,
	"crmMembers":              CrmMembers,
	"crmInbox":                CrmInbox,
	"crmReviews":              CrmReviews,
	"crmLoyalty":              CrmLoyalty,
	"crmReports":              CrmReports,
	"crmPromo":                CrmPromo,
	"crmEngagement":           CrmEngagement,
	"crmMemberReviews":        CrmMemberReviews,
	"crmPartners":             CrmPartners,
	"settings":                Settings,
	"settingsUsers":           SettingsUsers,
	"settingsRoles":           SettingsRoles,
	"settingsMenus":           SettingsMenus,
	"settingsBusiness":        SettingsBusiness,
	"settingsIntegrations":    SettingsIntegrations,
	"settingsAppearance":      SettingsAppearance,
	"settingsPaymentGateways": SettingsPaymentGateways,
	"settingsWaGateway":       SettingsWaGateway,
	"settingsAudit":           SettingsAudit,
	"shop":                    Shop,
	"ticketing":               Ticketing,
	"ticketingAdmin":          TicketingAdmin,
	"ticketingOperator":       TicketingOperator,
	"ticketingReports":        TicketingReports,
	"salesFunnel":             SalesFunnel,
	"promo":                   Promo,
	"dataroom":                Dataroom,
	"resort":                  Resort,
	"posWallet":               PosWallet,
	"gymExercises":            GymExercises,
	"gymRaces":                GymRaces,
	"gymIncentives":           GymIncentives,
	"gymPackages":             GymPackages,
	"gymCredits":              GymCredits,
	"gymRules":                GymRules,
	"gymScheduling":           GymScheduling,
	"gymCheckin":              GymCheckin,
	"hrisMaster":              HrisMaster,
	"hrisOrganization":        HrisOrganization,
	"hrisInsights":            HrisInsights,
	"hrisPerformanceAdmin":    HrisPerformanceAdmin,
	"posCatalogProducts":      PosCatalogProducts,
	"posLoyaltySettings":      PosLoyaltySettings,
	"settingsBilling":         SettingsBilling,
	"itemsCatalog":            ItemsCatalog,
	"itemsPr":                 ItemsPr,
	"itemsPrApproval":         ItemsPrApproval,
}
