// Package iamgen turns frontend/src/lib/iam/prefixes.ts into Go source. The
// generator (./gen) writes prefixes_gen.go; a test in package iam renders the
// TS file again and fails when the checked-in Go file has drifted.
package iamgen

import (
	"bytes"
	"errors"
	"fmt"
	"go/format"
	"regexp"
	"strings"
)

// Entry is one key of the IAM object.
type Entry struct {
	Key   string   // TS key, e.g. "gymPackages"
	Codes []string // menu code prefixes
}

var (
	blockComment = regexp.MustCompile(`(?s)/\*.*?\*/`)
	lineComment  = regexp.MustCompile(`(?m)//.*$`)
	objectBody   = regexp.MustCompile(`(?s)export const IAM = \{(.*?)\n\}\s*as const`)
	entryRe      = regexp.MustCompile(`(?s)([A-Za-z_][A-Za-z0-9_]*)\s*:\s*\[(.*?)\]`)
	stringRe     = regexp.MustCompile(`"([^"]*)"`)
)

// Parse extracts the IAM entries in source order.
func Parse(src string) ([]Entry, error) {
	src = blockComment.ReplaceAllString(src, "")
	src = lineComment.ReplaceAllString(src, "")
	m := objectBody.FindStringSubmatch(src)
	if m == nil {
		return nil, errors.New("iamgen: export const IAM = { ... } as const not found")
	}
	var out []Entry
	for _, e := range entryRe.FindAllStringSubmatch(m[1], -1) {
		entry := Entry{Key: e[1]}
		for _, s := range stringRe.FindAllStringSubmatch(e[2], -1) {
			entry.Codes = append(entry.Codes, s[1])
		}
		out = append(out, entry)
	}
	if len(out) == 0 {
		return nil, errors.New("iamgen: IAM object has no entries")
	}
	return out, nil
}

// GoName exports a TS key: "gymPackages" -> "GymPackages".
func GoName(key string) string {
	return strings.ToUpper(key[:1]) + key[1:]
}

// Render produces gofmt'ed Go source for package iam.
func Render(entries []Entry) ([]byte, error) {
	var b bytes.Buffer
	b.WriteString("// Code generated by go run ./internal/platform/iam/iamgen/gen; DO NOT EDIT.\n")
	b.WriteString("// Source: frontend/src/lib/iam/prefixes.ts\n\n")
	b.WriteString("package iam\n\n")
	b.WriteString("// Menu code prefixes, one var per key of IAM in prefixes.ts.\n")
	b.WriteString("var (\n")
	for _, e := range entries {
		fmt.Fprintf(&b, "\t%s = []string{%s}\n", GoName(e.Key), quoteAll(e.Codes))
	}
	b.WriteString(")\n\n")
	b.WriteString("// ByKey maps the TS key (e.g. \"gymPackages\") to its prefixes.\n")
	b.WriteString("var ByKey = map[string][]string{\n")
	for _, e := range entries {
		fmt.Fprintf(&b, "\t%q: %s,\n", e.Key, GoName(e.Key))
	}
	b.WriteString("}\n")
	return format.Source(b.Bytes())
}

func quoteAll(codes []string) string {
	parts := make([]string, len(codes))
	for i, c := range codes {
		parts[i] = fmt.Sprintf("%q", c)
	}
	return strings.Join(parts, ", ")
}
